### ISSUE TITLE
cooking pot does not show recipes if you click on the arrow with the REI mod

### ISSUE THREAD

**Issue by NeoFolia** [MehVahdJukaar/FarmersDelightRefabricated#51]
### Minecraft version

1.20.1

### Farmer's Delight version

FarmersDelight-1.20.1-2.1.1+refabricated

### Fabric Loader version

fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar

### Fabric API version

fabric-api-0.92.2+1.20.1.jar

### Description

![image](https://github.com/MehVahdJukaar/FarmersDelight/assets/147491823/7aa6bd06-9181-4bdb-ad4e-2df01a11e433)
I want to see recipes by clicking the arrow

### Mod list

REI
Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ChrysanthCow** [comment]
I forgot about this while doing integration, I'll look at this when I next touch this project.

**Comment by ChrysanthCow** [comment]
Fixed in 2.1.3
![image](https://github.com/user-attachments/assets/1b5d8915-fd89-48fb-a3c7-92d3ab35ee43)

**Comment by Qendolin** [comment]
This is still broken (or broken again). I'm getting a bunch of  
`[REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@...`   

Using FD 1.20.1-2.1.6 and REI 12.1.780

**Comment by AugustSaintFreytag** [comment]
Can we please get this reopened? Like @Qendolin, recipes made in the cooking pot can not be clicked in REI. None of the cooking pot recipes seem to correctly register.

```
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@3cf6c034 [farmersdelight:cooking/web_on_stick]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@bb926a4e [farmersdelight:cooking/vegetable_soup]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@1deb9454 [farmersdelight:cooking/vegetable_noodles]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@1d5cd7d5 [farmersdelight:cooking/undead_kebab]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@5dbb6287 [farmersdelight:cooking/tomato_sauce]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@e19feff [farmersdelight:cooking/stuffed_pumpkin_block]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@a81bc925 [farmersdelight:cooking/squid_ink_pasta]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@bbd9c7b [farmersdelight:cooking/soup_spider_eye]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@21a2766b [farmersdelight:cooking/soup_slime]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@e98a09f8 [farmersdelight:cooking/soup_rotten_flesh]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@aaf98f8 [farmersdelight:cooking/ratatouille]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@5c6652e [farmersdelight:cooking/rabbit_stew]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@28651301 [farmersdelight:cooking/punch_wither_berry_multiple]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@d47e3522 [farmersdelight:cooking/punch_spidereye_multiple]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@984645a9 [farmersdelight:cooking/punch_soul_berry_multiple]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@9b6ac75d [farmersdelight:cooking/punch_slimeapple_multiple]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@1d2f7173 [farmersdelight:cooking/punch_ghasttear_multiple]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@cafab0e9 [farmersdelight:cooking/pumpkin_soup]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@45b53fa9 [farmersdelight:cooking/pasta_with_slimeballs]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@46f0dab0 [farmersdelight:cooking/pasta_with_mutton_chop]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@1ced170b [farmersdelight:cooking/pasta_with_meatballs]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@cb4dc6bc [farmersdelight:cooking/noodle_soup]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@a4e0ae2b [farmersdelight:cooking/mushroom_stew]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@fd3ae4c9 [farmersdelight:cooking/mushroom_rice]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@2b76314f [farmersdelight:cooking/monster_mash]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@270fe529 [farmersdelight:cooking/hot_cocoa]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@1b82061d [farmersdelight:cooking/glow_berry_custard]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@66c28fea [farmersdelight:cooking/fried_rice]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@d2939198 [farmersdelight:cooking/fish_stew]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@b8374300 [farmersdelight:cooking/dumplings]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@10b32fff [farmersdelight:cooking/dog_food]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@c68b96f6 [farmersdelight:cooking/cooked_rice]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@f15236f [farmersdelight:cooking/chicken_soup]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@c1dd12eb [farmersdelight:cooking/cabbage_rolls]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@7b809ba6 [farmersdelight:cooking/bone_broth]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@c88e9aa3 [farmersdelight:cooking/beetroot_soup]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@f05f3cd0 [farmersdelight:cooking/beef_stew]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@b1280ff7 [farmersdelight:cooking/baked_cod_stew]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@8148700d [farmersdelight:cooking/apple_slime]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@8bb0a5f3 [farmersdelight:cooking/apple_cider]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@efa72fb7 [createfood:farmersdelight/cooking/yogurt_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@e8e95d94 [createfood:farmersdelight/cooking/yogurt_bottle_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@5981b67a [createfood:farmersdelight/cooking/yellow_gelatin_mix_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@9542eaf [createfood:farmersdelight/cooking/white_chocolate_fudge_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@55a7e3e7 [createfood:farmersdelight/cooking/white_chocolate_bottle_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@447317d [createfood:farmersdelight/cooking/vinegar_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@62d56ebe [createfood:farmersdelight/cooking/toffee_fudge_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@c9def787 [createfood:farmersdelight/cooking/toffee_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@697acbfe [createfood:farmersdelight/cooking/toffee_bucket_from_cooking_alt]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@6b6aa032 [createfood:farmersdelight/cooking/toffee_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@85028845 [createfood:farmersdelight/cooking/sugar_cane_juice_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@fa051d6 [createfood:farmersdelight/cooking/squid_ink_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@131fc9d9 [createfood:farmersdelight/cooking/sour_cream_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@dce2f17c [createfood:farmersdelight/cooking/slime_bucket_from_cooking]
[18:20:04] [REI-ReloadPlugins/ERROR]: [REI] Failed to fill display for recipe: vectorwing.farmersdelight.common.crafting.CookingPotRecipe@2750c255 [createfood:farmersdelight/cooking/salt_from_cooking]
```
